baseurl: /rooted

collections:
  weeks:
    permalink: /:name/
    output: true

defaults:
  -
    scope:
      path: ""
      type: "weeks" # a collection in your site, in plural form
    values:
      layout: "week"